name: Deploy to Azure

on:
  push:
    branches:
    - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout repository

    - uses: actions/setup-node@v2
      with:
        node-version: '12'

    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present

    - name: 'Deploy to Azure'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: TemplateBot
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
